name: PushToProd

permissions:
  id-token: write
on:
  push:
    inputs:
      website:
        description: 'Name of the S3 bucket aka website to publish to'
        default: 'footsteps.live'
  workflow_dispatch:
    inputs:
      website:
        description: 'Name of the S3 bucket aka website to publish to'
        required: true
        default: 'footsteps.live'
        options:
        - 'footsteps.live'

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    env:
      STEP_S3_BUCKET: ${{ github.event.inputs.website }}
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
    - name: Build Assets
      run: python3 ./.github/scripts/build-assets.py
    - name: S3Sync
      run: aws s3 sync public s3://$STEP_S3_BUCKET --dry-run
